### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Subhrabiswas** [dronefreak/VisDrone-dataset-python-toolkit#1]
When I run the script file for conversion, i am getting this error
![IMG_20200427_105617](https://user-images.githubusercontent.com/23023971/80336787-dc7dbb00-8875-11ea-9880-4a0a762af3b4.jpg)

Could you please help me out with this.

**Comment by dronefreak** [comment]
Hi @Subhrabiswas 

This is a classic file-not-found error. Could you make sure that your directory structure was like:
```
VisDrone2019-DET-train
---annotations
---images

convertVis_to_xml.py
```
Also, if you could add a print flag to line 74 of your code, printing the addresses of your image files, that will help you better debug your code.
