### ISSUE TITLE
Plotting_ ncorrect Bounding_Box 

### ISSUE THREAD

**Issue by sharoseali** [dronefreak/VisDrone-dataset-python-toolkit#3]
HI, @dronefreak I am trying to train visdrone  data on different object detection architectures. For that reason I have to convert it into first pascal VOC, I used your conversion script, thanks for your work, but  When I plot the bounding box after conversion, it's showing me wrong bounding box. Can you please review or share plotting script. following are the vis drone-TXT annotation file and corresponding PASCAL VOC XML files.

![image](https://user-images.githubusercontent.com/19869426/86334031-5c007f80-bc55-11ea-880c-1060de47d5ba.png)

Pascal VOC:  Are x-min, y-min x-max y-max are correct?

![image](https://user-images.githubusercontent.com/19869426/86334135-7aff1180-bc55-11ea-915d-dad19049a127.png)

Thanks

**Comment by dronefreak** [comment]
Hi @sharoseali 

I double checked the bounding boxes, they seem to look fine to me, as I had visualized them on images, and also trained a object detection algorithm on them. Original bounding box notation was meant to contain the width and height of the boxes, whereas the PASCAL-VOC notation has only the minima and the maxima of the bounding boxes, hence the conversion is required.

**Comment by sharoseali** [comment]
OK, that's good to hear, thanks......  can you please share the bounding box visualizing script. The one that I am using is not drawing the correct bounding box. I also uploaded on Robo-flow to see my data, Also it didn't show correct visualization. Some times it says, your bounding points lie outside the image size, I don't know whether it resize the image or not, so can you share the plotting script, please?

**Comment by dronefreak** [comment]
Hi,

Just uncomment this [line](https://github.com/dronefreak/VisDrone-dataset-python-toolkit/blob/5470c25ec479eb7740b9d918ba6dded74b71ef63/convertVis_to_xml.py#L87) and the outputs will have the boxes

**Comment by karen-gishyan** [comment]
Hello @dronefreak, @sharoseali. I also encountered the same problem while converting from the txt annotations to PASCAL VOX XML.  When I upload on Roboflow to check the bounding boxes, surprisingly all of the boxes seem to be shifted. Would be glad if you could check again. Thanks.

**Comment by dronefreak** [comment]
Hello,

I am not sure how Roboflow works but these scripts are meant to work with TF's Object Detection API, and I have personally tested them by fine-tuning an algorithm. Maybe if you could show me some outputs (visual), I could help you with the annotations.

**Comment by karen-gishyan** [comment]
![1](https://user-images.githubusercontent.com/52350350/86392091-eecc0900-bcab-11ea-92be-ae9fefed88ad.png)
![2](https://user-images.githubusercontent.com/52350350/86392101-f390bd00-bcab-11ea-9864-721a9ac2679f.png)
@dronefreak when uploading the image and the corresponding XML, weirdly they do not match., however I checked the image bounding boxes of your code and they seem to be completely fine. This might be a Roboflow issue.

**Comment by dronefreak** [comment]
This indeed looks weird and I have no idea why this is happening, as I have never used Roboflow before.
Thanks for the information.

**Comment by sharoseali** [comment]
HI @dronefreak and @karen-gishyan , yes the script is working fine thanks for your response. There is a problem with the Roboflow portal. I again convert pascal VOC annotations to YOLO format with this conversion [tool](https://github.com/hai-h-nguyen/Yolo2Pascal-annotation-conversion). After conversion,  The YOLO format annotations are also looking fine now. 

![image](https://user-images.githubusercontent.com/19869426/86416045-8ee85900-bcd1-11ea-9282-fc0d0cfbc478.png)


![image](https://user-images.githubusercontent.com/19869426/86416149-e4bd0100-bcd1-11ea-9bbe-39a292487944.png)

Thanks again. Closing the issue......
