### ISSUE TITLE
Evaluation Tools

### ISSUE THREAD

**Issue by ChenhongyiYang** [dronefreak/VisDrone-dataset-python-toolkit#4]
Hi,  thanks for your great work.

I'm wondering if the evaluation code can produce the same number as the official Matlab evaluation code?

**Comment by dronefreak** [comment]
Hi @ChenhongyiYang 

I have not created an evaluation tool in Python yet, as I did not have time for it.
I will focus on this aspect now and I will let you know. Perhaps we can collaborate and work together. 
Please let me know if it works for you.
