### ISSUE TITLE
Confirmation of Bounding boxes generation

### ISSUE THREAD

**Issue by hlmhlr** [dronefreak/VisDrone-dataset-python-toolkit#5]
Hi, 

First of all thank you for putting your efforts towards "generation of xml files". I have a basic query (apology for such a simple question but i am newbie here): As per README file, once xml files are generated for all images, two figures are displayed, "Original Image" and "With PASCAL-style bounding boxes". In my case, all xml files are generated but images do not contain boxes. Am i missing anything or there is some different procedure? I am using same visdrone2019 dataset. 

I shall be grateful for your kind response.

Thanks, 
-- | --

**Comment by dronefreak** [comment]
Hi @hlmhlr 

Sorry for the later reply. You can generate visualizations by uncommenting Line 87 `#cv2.rectangle(img, new_coords_min, new_coords_max, color, thickness)` in `convertVis_to_xml.py`. I keep it commented because the images with BBs are primarily meant for visualization, whereas the training data requires the BBs in either YOLO or PASCAL format. Hope this helps!

**Comment by dronefreak** [comment]
Closing this as seems resolved :D

**Comment by hlmhlr** [comment]
> Hi @hlmhlr
> 
> Sorry for the later reply. You can generate visualizations by uncommenting Line 87 `#cv2.rectangle(img, new_coords_min, new_coords_max, color, thickness)` in `convertVis_to_xml.py`. I keep it commented because the images with BBs are primarily meant for visualization, whereas the training data requires the BBs in either YOLO or PASCAL format. Hope this helps!

Hi @dronefreak, 
Bundle of thanks for your positive response. Its solved. Also, need to know your comments about the bboxes in the visdrone, see for example the attached image, where multiple objects are annotated in a single bbox. So how we may interpret them from data processing point of view? I would be grateful for your comments.
![0000002_00448_d_0000015](https://user-images.githubusercontent.com/67587354/104370157-ba6cbb80-551e-11eb-8db5-4f232b188330.jpg)
  Thanks,
