### ISSUE TITLE
Opencv error when i run convertVis_to_xml.py

### ISSUE THREAD

**Issue by enesyildirim7** [dronefreak/VisDrone-dataset-python-toolkit#7]

**Comment by enesyildirim7** [comment]
When I run convertVis_to_xml.py, I get AttributeError: 'NoneType' object has no attribute 'shape' error on line 75.

**Comment by dronefreak** [comment]
Hi @enesyildirim7 
This means that the code is unable to find the images in the expected location.
Please make sure you have a consistent directory structure for the dataset. You could simply print the path in the .py code which is being used by the code to look for the dataset, that will give you a good idea. Hope this helps!

**Comment by enesyildirim7** [comment]
@dronefreak 
I solved the error using the Pillow module instead of Opencv. I could not find the picture depth in Pillow, so I fixed the picture depth to 3 manually.
